export JAVA_HOME=/usr/java/default

export EXPORT_PREFIX=/export

export HADOOP_PREFIX=/usr/local/hadoop
export HADOOP_COMMON_HOME=$HADOOP_PREFIX
export HADOOP_HDFS_HOME=$HADOOP_PREFIX
export HADOOP_MAPRED_HOME=$HADOOP_PREFIX
export HADOOP_YARN_HOME=$HADOOP_PREFIX
export HADOOP_CONF_DIR=$HADOOP_PREFIX/etc/hadoop
export YARN_CONF_DIR=$HADOOP_PREFIX/etc/hadoop

export HADOOP_LOG_DIR=${EXPORT_PREFIX}/log/hdfs
export YARN_LOG_DIR=${EXPORT_PREFIX}/log/yarn
export HADOOP_MAPRED_LOG_DIR=${EXPORT_PREFIX}/log/mapred


